name: Setup Erlang
description: Set up a specific version of OTP
author: ErlGang
inputs:
  otp-version:
    description: Exact version of OTP to use
outputs:
  otp-version:
    description: Exact version of OTP that was installed
    value: ${{ steps.install-otp.outputs.otp-version }}
runs:
  using: "composite"
  steps:
    - id: install-otp
      shell: bash
      run: ${{ github.action_path }}/install-otp.sh ${{ inputs.otp-version }}
