name: Setup OTP
description: Set up a specific version of Erlang/OTP
author: ErlGang
branding:
  color: red
  icon: code
inputs:
  otp-version:
    description: Exact version of OTP to use
runs:
  using: "composite"
  steps:
    - id: install-otp
      shell: bash
      run: ${{ github.action_path }}/install-otp.sh ${{ inputs.otp-version }}
